### ISSUE TITLE
Not Participating in Hacktoberfest2023 

### ISSUE THREAD

**Issue by Rahullkumr** [prashantjagtap2909/Connecting#16]
# This is what I got from the [Hacktoberfest](https://hacktoberfest.com) website

![np](https://github.com/prashantjagtap2909/Connecting/assets/42183055/45ebd411-e5d2-4170-874a-a39e77adb7af)
![info](https://github.com/prashantjagtap2909/Connecting/assets/42183055/908f9c35-9d16-41d1-9e55-0cd743f91a1e)

**Comment by Rahullkumr** [comment]
# There is spelling mistake 

It should be `hacktoberfest` not hackoberfest 
<br><br>

![spelling mistake](https://github.com/prashantjagtap2909/Connecting/assets/42183055/6c27fdd9-369c-49d2-89da-acee4937540e)

**Comment by prashantjagtap2909** [comment]
Thank you.
Now you can contribute...
